### ISSUE TITLE
Negative negative counts?

### ISSUE THREAD

**Issue by Jmuccigr** [COVID19Tracking/covid-tracking-dash#4]
March 30 data for MT and WI show negative daily totals for negative test results (meaning negativeIncrease < 0). Is that an error or a recount from earlier days, or something else?

**Comment by eric-czech** [comment]
For WI for example, you can look at the screenshots showing the state captured on those days for https://www.dhs.wisconsin.gov/outbreaks/index.htm at: https://covidtracking.com/data/state/wisconsin/#history.  That shows that the decreases are real, but I don't know why they occurred.  I imagine the same is true for MI, which you could check out at https://covidtracking.com/data/.  

Perhaps the state sites themselves will explain what happened, otherwise I would say to file an issue in the [issues](https://github.com/COVID19Tracking/issues/issues) repo if you really need an explanation as someone doing state-level data curation might know what that means.
